[[redirects]]
  from = "/home"
  to = "/index.html"
  status = 200
  force = false
  
[[redirects]]
  from = "/timeline"
  to = "/index.html"
  status = 200
  force = false
  
[[redirects]]
  from = "/skills-projects"
  to = "/index.html"
  status = 200
  force = false
  
[[redirects]]
  from = "/contact"
  to = "/index.html"
  status = 200
  force = false
  
[[redirects]]
  from = "/privacy"
  to = "/index.html"
  status = 200
  force = false
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false